adminUser:
  password: vault:goatautumn/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jennifer@anonshells.com
  token: vault:goatautumn/pipelineUser:token
  username: ImagitBOT
prow:
  hmacToken: vault:goatautumn/prow:hmacToken
