adminUser:
  password: vault:goatautumn/adminUser:password
  username: jadmin
docker:
  email: support@anonshells.com
  password: vault:goatautumn/docker:password
  url: https://index.docker.io/v1/
  username: anonshells
enableDocker: true
pipelineUser:
  email: jennifer@anonshells.com
  token: vault:goatautumn/pipelineUser:token
  username: ImagitBOT
prow:
  hmacToken: vault:goatautumn/prow:hmacToken
